CREATE TABLE IF NOT EXISTS lta.api_endpoint (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    api_code VARCHAR(10) NOT NULL,
    api_name VARCHAR(100) NOT NULL,
    endpoint_url TEXT NOT NULL,
    schedule_type VARCHAR(20) NOT NULL,
    interval_minutes INTEGER,
    schedule_rule VARCHAR(100),
    raw_save_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    db_write_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_api_endpoint PRIMARY KEY (uid),
    CONSTRAINT uq_api_endpoint_api_code UNIQUE (api_code)
);

CREATE TABLE IF NOT EXISTS lta.collection_run (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    api_endpoint_uid UUID NOT NULL,
    run_mode VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    scheduled_time TIMESTAMPTZ,
    attempt_no SMALLINT NOT NULL DEFAULT 1,
    request_start_time TIMESTAMPTZ NOT NULL,
    request_end_time TIMESTAMPTZ,
    source_updated_time TIMESTAMPTZ,
    http_status SMALLINT,
    page_count INTEGER NOT NULL DEFAULT 0,
    record_count INTEGER NOT NULL DEFAULT 0,
    response_bytes BIGINT NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    snapshot_complete BOOLEAN NOT NULL DEFAULT FALSE,
    consistency_status VARCHAR(20),
    retry_count SMALLINT NOT NULL DEFAULT 0,
    error_message TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_collection_run PRIMARY KEY (uid),
    CONSTRAINT fk_collection_run_endpoint FOREIGN KEY (api_endpoint_uid) REFERENCES lta.api_endpoint(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_collection_run_mode CHECK (run_mode IN ('SCHEDULED','MANUAL_TEST','BACKFILL')),
    CONSTRAINT ck_collection_run_attempt CHECK (attempt_no >= 1),
    CONSTRAINT ck_collection_run_page_count CHECK (page_count >= 0),
    CONSTRAINT ck_collection_run_record_count CHECK (record_count >= 0),
    CONSTRAINT ck_collection_run_response_bytes CHECK (response_bytes >= 0),
    CONSTRAINT ck_collection_run_retry_count CHECK (retry_count >= 0)
);

CREATE TABLE IF NOT EXISTS lta.collection_page_log (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    run_uid UUID NOT NULL,
    page_no INTEGER NOT NULL,
    skip_value INTEGER NOT NULL,
    request_start_time TIMESTAMPTZ NOT NULL,
    request_end_time TIMESTAMPTZ,
    source_updated_time TIMESTAMPTZ,
    http_status SMALLINT,
    record_count INTEGER NOT NULL DEFAULT 0,
    response_bytes BIGINT NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_collection_page_log PRIMARY KEY (uid),
    CONSTRAINT fk_collection_page_log_run FOREIGN KEY (run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT uq_collection_page_log_page UNIQUE (run_uid, page_no),
    CONSTRAINT uq_collection_page_log_skip UNIQUE (run_uid, skip_value),
    CONSTRAINT ck_collection_page_log_page_no CHECK (page_no >= 1),
    CONSTRAINT ck_collection_page_log_skip CHECK (skip_value >= 0),
    CONSTRAINT ck_collection_page_log_record_count CHECK (record_count >= 0),
    CONSTRAINT ck_collection_page_log_response_bytes CHECK (response_bytes >= 0)
);

CREATE TABLE IF NOT EXISTS lta.collection_artifact (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    run_uid UUID NOT NULL,
    artifact_type VARCHAR(30) NOT NULL,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    sha256 CHAR(64),
    compression_type VARCHAR(20) NOT NULL DEFAULT 'NONE',
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_collection_artifact PRIMARY KEY (uid),
    CONSTRAINT fk_collection_artifact_run FOREIGN KEY (run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_collection_artifact_type CHECK (artifact_type IN ('RAW_JSON','DATA_FILE','SUMMARY')),
    CONSTRAINT ck_collection_artifact_size CHECK (file_size_bytes >= 0)
);

CREATE TABLE IF NOT EXISTS lta.study_area (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    ciq_code VARCHAR(20) NOT NULL,
    zone_code VARCHAR(20) NOT NULL,
    area_name VARCHAR(150) NOT NULL,
    corridor_name VARCHAR(150),
    geom GEOMETRY(MULTIPOLYGON,4326) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_study_area PRIMARY KEY (uid),
    CONSTRAINT uq_study_area_business UNIQUE (ciq_code, zone_code, area_name),
    CONSTRAINT ck_study_area_ciq CHECK (ciq_code IN ('WOODLANDS','TUAS')),
    CONSTRAINT ck_study_area_zone CHECK (zone_code IN ('CORE','APPROACH','CORRIDOR'))
);

CREATE TABLE IF NOT EXISTS lta.traffic_link (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    link_id VARCHAR(50) NOT NULL,
    road_name VARCHAR(255),
    road_category SMALLINT,
    start_lon NUMERIC(20,16) NOT NULL,
    start_lat NUMERIC(20,16) NOT NULL,
    end_lon NUMERIC(20,16) NOT NULL,
    end_lat NUMERIC(20,16) NOT NULL,
    geom GEOMETRY(LINESTRING,4326) NOT NULL,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_traffic_link PRIMARY KEY (uid),
    CONSTRAINT uq_traffic_link_link_id UNIQUE (link_id),
    CONSTRAINT ck_traffic_link_start_lon CHECK (start_lon BETWEEN -180 AND 180),
    CONSTRAINT ck_traffic_link_end_lon CHECK (end_lon BETWEEN -180 AND 180),
    CONSTRAINT ck_traffic_link_start_lat CHECK (start_lat BETWEEN -90 AND 90),
    CONSTRAINT ck_traffic_link_end_lat CHECK (end_lat BETWEEN -90 AND 90),
    CONSTRAINT ck_traffic_link_seen_time CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.traffic_link_scope (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    link_uid UUID NOT NULL,
    area_uid UUID NOT NULL,
    match_method VARCHAR(30) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_traffic_link_scope PRIMARY KEY (uid),
    CONSTRAINT fk_traffic_link_scope_link FOREIGN KEY (link_uid) REFERENCES lta.traffic_link(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_traffic_link_scope_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT uq_traffic_link_scope UNIQUE (link_uid, area_uid),
    CONSTRAINT ck_traffic_link_scope_method CHECK (match_method IN ('SPATIAL','MANUAL','ROAD_NAME'))
);

CREATE TABLE IF NOT EXISTS lta.traffic_speed_observation (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    snapshot_time TIMESTAMPTZ NOT NULL,
    link_uid UUID NOT NULL,
    speed_band SMALLINT NOT NULL,
    minimum_speed SMALLINT,
    maximum_speed SMALLINT,
    source_updated_time TIMESTAMPTZ,
    run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_traffic_speed_observation PRIMARY KEY (uid),
    CONSTRAINT fk_traffic_speed_observation_link FOREIGN KEY (link_uid) REFERENCES lta.traffic_link(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_traffic_speed_observation_run FOREIGN KEY (run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT uq_traffic_speed_observation UNIQUE (snapshot_time, link_uid),
    CONSTRAINT ck_traffic_speed_band CHECK (speed_band BETWEEN 1 AND 8),
    CONSTRAINT ck_traffic_speed_min CHECK (minimum_speed IS NULL OR minimum_speed >= 0),
    CONSTRAINT ck_traffic_speed_max CHECK (maximum_speed IS NULL OR maximum_speed >= 0),
    CONSTRAINT ck_traffic_speed_range CHECK (minimum_speed IS NULL OR maximum_speed IS NULL OR maximum_speed >= minimum_speed)
);

CREATE TABLE IF NOT EXISTS lta.travel_time_segment (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(20) NOT NULL,
    direction SMALLINT NOT NULL,
    far_end_point VARCHAR(255) NOT NULL,
    start_point VARCHAR(255) NOT NULL,
    end_point VARCHAR(255) NOT NULL,
    area_uid UUID,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_travel_time_segment PRIMARY KEY (uid),
    CONSTRAINT fk_travel_time_segment_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT uq_travel_time_segment UNIQUE (name, direction, far_end_point, start_point, end_point),
    CONSTRAINT ck_travel_time_segment_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.travel_time_observation (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    snapshot_time TIMESTAMPTZ NOT NULL,
    segment_uid UUID NOT NULL,
    est_time_min SMALLINT NOT NULL,
    run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_travel_time_observation PRIMARY KEY (uid),
    CONSTRAINT fk_travel_time_observation_segment FOREIGN KEY (segment_uid) REFERENCES lta.travel_time_segment(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_travel_time_observation_run FOREIGN KEY (run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT uq_travel_time_observation UNIQUE (snapshot_time, segment_uid),
    CONSTRAINT ck_travel_time_est CHECK (est_time_min >= 0)
);

CREATE TABLE IF NOT EXISTS lta.traffic_incident_event (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    event_fingerprint CHAR(64) NOT NULL,
    type VARCHAR(100) NOT NULL,
    latitude NUMERIC(20,16) NOT NULL,
    longitude NUMERIC(20,16) NOT NULL,
    geom GEOMETRY(POINT,4326) NOT NULL,
    message TEXT NOT NULL,
    area_uid UUID,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    resolved_time TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_run_uid UUID NOT NULL,
    last_run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_traffic_incident_event PRIMARY KEY (uid),
    CONSTRAINT uq_traffic_incident_fingerprint UNIQUE (event_fingerprint),
    CONSTRAINT fk_traffic_incident_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_traffic_incident_first_run FOREIGN KEY (first_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_traffic_incident_last_run FOREIGN KEY (last_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_traffic_incident_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_traffic_incident_lon CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_traffic_incident_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.vms_equipment (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    equipment_id VARCHAR(100) NOT NULL,
    latitude NUMERIC(20,16) NOT NULL,
    longitude NUMERIC(20,16) NOT NULL,
    geom GEOMETRY(POINT,4326) NOT NULL,
    area_uid UUID,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_vms_equipment PRIMARY KEY (uid),
    CONSTRAINT uq_vms_equipment_id UNIQUE (equipment_id),
    CONSTRAINT fk_vms_equipment_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_vms_equipment_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_vms_equipment_lon CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_vms_equipment_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.vms_message_state (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    equipment_uid UUID NOT NULL,
    message TEXT NOT NULL,
    message_hash CHAR(64) NOT NULL,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    ended_time TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_run_uid UUID NOT NULL,
    last_run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_vms_message_state PRIMARY KEY (uid),
    CONSTRAINT fk_vms_message_equipment FOREIGN KEY (equipment_uid) REFERENCES lta.vms_equipment(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_vms_message_first_run FOREIGN KEY (first_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_vms_message_last_run FOREIGN KEY (last_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_vms_message_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.faulty_traffic_light_event (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    alarm_id VARCHAR(100) NOT NULL,
    node_id VARCHAR(100) NOT NULL,
    fault_type SMALLINT,
    source_start_time TIMESTAMPTZ NOT NULL,
    source_end_time TIMESTAMPTZ,
    message TEXT,
    area_uid UUID,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    resolved_time TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_run_uid UUID NOT NULL,
    last_run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_faulty_traffic_light_event PRIMARY KEY (uid),
    CONSTRAINT uq_faulty_traffic_light_alarm UNIQUE (alarm_id),
    CONSTRAINT fk_faulty_traffic_light_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_faulty_traffic_light_first_run FOREIGN KEY (first_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_faulty_traffic_light_last_run FOREIGN KEY (last_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_faulty_traffic_light_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.road_work_event (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    svc_dept VARCHAR(255),
    road_name VARCHAR(255),
    other TEXT,
    area_uid UUID,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    resolved_time TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_run_uid UUID NOT NULL,
    last_run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_road_work_event PRIMARY KEY (uid),
    CONSTRAINT uq_road_work_event_id UNIQUE (event_id),
    CONSTRAINT fk_road_work_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_road_work_first_run FOREIGN KEY (first_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_road_work_last_run FOREIGN KEY (last_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_road_work_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_road_work_seen CHECK (last_seen_time >= first_seen_time)
);

CREATE TABLE IF NOT EXISTS lta.traffic_flow_file (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    check_month DATE NOT NULL,
    run_uid UUID NOT NULL,
    download_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    sha256 CHAR(64),
    is_new_version BOOLEAN NOT NULL DEFAULT TRUE,
    source_period VARCHAR(100),
    downloaded_time TIMESTAMPTZ NOT NULL,
    parse_status VARCHAR(20) NOT NULL DEFAULT 'NOT_PARSED',
    parse_message TEXT,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_traffic_flow_file PRIMARY KEY (uid),
    CONSTRAINT uq_traffic_flow_check_month UNIQUE (check_month),
    CONSTRAINT fk_traffic_flow_run FOREIGN KEY (run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_traffic_flow_month CHECK (EXTRACT(DAY FROM check_month) = 1),
    CONSTRAINT ck_traffic_flow_size CHECK (file_size_bytes >= 0),
    CONSTRAINT ck_traffic_flow_parse_status CHECK (parse_status IN ('NOT_PARSED','PARSED','FAILED'))
);

CREATE TABLE IF NOT EXISTS lta.road_opening_event (
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    svc_dept VARCHAR(255),
    road_name VARCHAR(255),
    other TEXT,
    area_uid UUID,
    first_seen_time TIMESTAMPTZ NOT NULL,
    last_seen_time TIMESTAMPTZ NOT NULL,
    resolved_time TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    first_run_uid UUID NOT NULL,
    last_run_uid UUID NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_road_opening_event PRIMARY KEY (uid),
    CONSTRAINT uq_road_opening_event_id UNIQUE (event_id),
    CONSTRAINT fk_road_opening_area FOREIGN KEY (area_uid) REFERENCES lta.study_area(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_road_opening_first_run FOREIGN KEY (first_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT fk_road_opening_last_run FOREIGN KEY (last_run_uid) REFERENCES lta.collection_run(uid) ON DELETE RESTRICT,
    CONSTRAINT ck_road_opening_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_road_opening_seen CHECK (last_seen_time >= first_seen_time)
);
