COMMENT ON TABLE lta.api_endpoint IS 'LTA DataMall接口配置主表，用于保存接口编号、名称、URL、采集频率、Raw文件保存策略以及数据库写入策略。';
COMMENT ON COLUMN lta.api_endpoint.uid IS '本表UUID主键，由PostgreSQL自动生成，供其他表通过UUID建立关联。';
COMMENT ON COLUMN lta.api_endpoint.api_code IS '项目内部接口编号，例如API01；属于项目业务编号，不作为数据库主键。';
COMMENT ON COLUMN lta.api_endpoint.api_name IS 'LTA DataMall接口名称，用于任务识别与审计展示。';
COMMENT ON COLUMN lta.api_endpoint.endpoint_url IS 'LTA DataMall接口完整请求URL，用于发起数据采集请求。';
COMMENT ON COLUMN lta.api_endpoint.schedule_type IS '采集调度类型，例如MINUTES、HOURLY、DAILY或MONTH_END。';
COMMENT ON COLUMN lta.api_endpoint.interval_minutes IS '固定分钟采集周期，仅分钟或小时型任务使用。';
COMMENT ON COLUMN lta.api_endpoint.schedule_rule IS '特殊调度规则，例如每月最后一天LAST_DAY_OF_MONTH。';
COMMENT ON COLUMN lta.api_endpoint.raw_save_enabled IS '是否将LTA接口原始响应作为外部Raw文件永久保存。';
COMMENT ON COLUMN lta.api_endpoint.db_write_enabled IS '是否将清洗后的LTA业务数据写入PostgreSQL。';
COMMENT ON COLUMN lta.api_endpoint.enabled IS '当前LTA接口采集任务是否启用。';
COMMENT ON COLUMN lta.api_endpoint.description IS '接口用途、研究价值及其他补充说明。';
COMMENT ON COLUMN lta.api_endpoint.create_time IS '本条接口配置首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.api_endpoint.update_time IS '本条接口配置最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.collection_run IS 'LTA所有接口统一采集任务主日志表，一次接口调度对应一条记录，用于记录请求、数量、完整性、重试和错误。';
COMMENT ON COLUMN lta.collection_run.uid IS '本次采集任务UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.collection_run.api_endpoint_uid IS '关联lta.api_endpoint.uid的UUID外键，用于确定本次任务所属接口。';
COMMENT ON COLUMN lta.collection_run.run_mode IS '任务运行模式，允许SCHEDULED、MANUAL_TEST或BACKFILL。';
COMMENT ON COLUMN lta.collection_run.scheduled_time IS '系统计划执行本轮采集的时间，不是实际HTTP请求时间。';
COMMENT ON COLUMN lta.collection_run.attempt_no IS '本轮任务请求尝试序号，从1开始。';
COMMENT ON COLUMN lta.collection_run.request_start_time IS '本轮实际HTTP请求开始时间。';
COMMENT ON COLUMN lta.collection_run.request_end_time IS '本轮实际HTTP请求结束时间。';
COMMENT ON COLUMN lta.collection_run.source_updated_time IS 'LTA响应声明的源数据更新时间。';
COMMENT ON COLUMN lta.collection_run.http_status IS 'LTA HTTP响应状态码，用于请求审计。';
COMMENT ON COLUMN lta.collection_run.page_count IS '本轮成功或尝试获取的分页总数。';
COMMENT ON COLUMN lta.collection_run.record_count IS '本轮采集获得的LTA业务记录总数。';
COMMENT ON COLUMN lta.collection_run.response_bytes IS '本轮HTTP响应体总字节数。';
COMMENT ON COLUMN lta.collection_run.success IS '本轮接口采集与数据库处理是否成功。';
COMMENT ON COLUMN lta.collection_run.snapshot_complete IS '本轮数据是否形成完整科研快照。';
COMMENT ON COLUMN lta.collection_run.consistency_status IS '多页源时间一致性状态，例如SINGLE、MIXED或NA。';
COMMENT ON COLUMN lta.collection_run.retry_count IS '本轮任务发生的重试次数。';
COMMENT ON COLUMN lta.collection_run.error_message IS '本轮失败时的错误摘要，不记录API密钥等敏感信息。';
COMMENT ON COLUMN lta.collection_run.create_time IS '本条采集任务日志首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.collection_run.update_time IS '本条采集任务日志最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.collection_page_log IS '接口分页采集审计表，记录TrafficSpeedBands每个$skip请求，用于定位漏页、失败页和跨页源时间变化。';
COMMENT ON COLUMN lta.collection_page_log.uid IS '本条分页审计记录UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.collection_page_log.run_uid IS '关联lta.collection_run.uid的UUID外键，对应本轮采集主任务。';
COMMENT ON COLUMN lta.collection_page_log.page_no IS '本轮采集内部分页序号，从1开始。';
COMMENT ON COLUMN lta.collection_page_log.skip_value IS '发送给LTA DataMall分页请求的$skip值。';
COMMENT ON COLUMN lta.collection_page_log.request_start_time IS '本页实际HTTP请求开始时间。';
COMMENT ON COLUMN lta.collection_page_log.request_end_time IS '本页实际HTTP请求结束时间。';
COMMENT ON COLUMN lta.collection_page_log.source_updated_time IS '本页LTA响应声明的源数据更新时间。';
COMMENT ON COLUMN lta.collection_page_log.http_status IS '本页LTA HTTP响应状态码。';
COMMENT ON COLUMN lta.collection_page_log.record_count IS '本页LTA响应包含的业务记录数。';
COMMENT ON COLUMN lta.collection_page_log.response_bytes IS '本页HTTP响应体字节数。';
COMMENT ON COLUMN lta.collection_page_log.success IS '本页请求及解析是否成功。';
COMMENT ON COLUMN lta.collection_page_log.error_message IS '本页失败时的错误摘要，不包含密钥。';
COMMENT ON COLUMN lta.collection_page_log.create_time IS '本条分页日志首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.collection_page_log.update_time IS '本条分页日志最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.collection_artifact IS '采集原始文件与数据文件元数据登记表，仅保存路径、大小和SHA256，不直接保存大型Raw JSON。';
COMMENT ON COLUMN lta.collection_artifact.uid IS '本条采集文件登记UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.collection_artifact.run_uid IS '关联lta.collection_run.uid的UUID外键，表示生成该文件的采集任务。';
COMMENT ON COLUMN lta.collection_artifact.artifact_type IS '文件用途类型：RAW_JSON、DATA_FILE或SUMMARY。';
COMMENT ON COLUMN lta.collection_artifact.file_name IS '采集产物文件名称。';
COMMENT ON COLUMN lta.collection_artifact.file_path IS '采集产物在外部文件系统中的完整或受控相对路径。';
COMMENT ON COLUMN lta.collection_artifact.file_size_bytes IS '采集产物文件大小，单位为字节。';
COMMENT ON COLUMN lta.collection_artifact.sha256 IS '采集产物内容SHA256校验值，用于完整性审计。';
COMMENT ON COLUMN lta.collection_artifact.compression_type IS '采集产物压缩类型，未压缩时为NONE。';
COMMENT ON COLUMN lta.collection_artifact.create_time IS '本条文件登记首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.collection_artifact.update_time IS '本条文件登记最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.study_area IS 'Woodlands CIQ与Tuas CIQ科研研究区域空间主表，用于保存CORE、APPROACH、CORRIDOR等经确认的正式研究区域。';
COMMENT ON COLUMN lta.study_area.uid IS '研究区域UUID主键，由PostgreSQL自动生成，供业务表以UUID关联。';
COMMENT ON COLUMN lta.study_area.ciq_code IS 'CIQ关卡代码，允许WOODLANDS或TUAS。';
COMMENT ON COLUMN lta.study_area.zone_code IS '研究分区代码，允许CORE、APPROACH或CORRIDOR。';
COMMENT ON COLUMN lta.study_area.area_name IS '经研究人员确认的研究区域名称。';
COMMENT ON COLUMN lta.study_area.corridor_name IS '研究区域所属交通走廊名称。';
COMMENT ON COLUMN lta.study_area.geom IS '研究区域WGS84多面空间几何，PostGIS MULTIPOLYGON，SRID 4326。';
COMMENT ON COLUMN lta.study_area.active IS '该研究区域当前是否参与空间筛选。';
COMMENT ON COLUMN lta.study_area.create_time IS '本条研究区域首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.study_area.update_time IS '本条研究区域最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.traffic_link IS 'TrafficSpeedBands道路Link静态空间主表，保存LTA道路分段业务编号、道路属性、端点及线几何；不保存动态速度。';
COMMENT ON COLUMN lta.traffic_link.uid IS '道路Link数据库UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.traffic_link.link_id IS 'LTA TrafficSpeedBands返回的LinkID源系统业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.traffic_link.road_name IS 'LTA返回的道路名称，用于道路检索与研究分组。';
COMMENT ON COLUMN lta.traffic_link.road_category IS 'LTA返回的道路类别代码。';
COMMENT ON COLUMN lta.traffic_link.start_lon IS 'LTA道路起点经度，WGS84，NUMERIC(20,16)，用于构造线几何。';
COMMENT ON COLUMN lta.traffic_link.start_lat IS 'LTA道路起点纬度，WGS84，NUMERIC(20,16)，用于构造线几何。';
COMMENT ON COLUMN lta.traffic_link.end_lon IS 'LTA道路终点经度，WGS84，NUMERIC(20,16)，用于构造线几何。';
COMMENT ON COLUMN lta.traffic_link.end_lat IS 'LTA道路终点纬度，WGS84，NUMERIC(20,16)，用于构造线几何。';
COMMENT ON COLUMN lta.traffic_link.geom IS '由起点至终点按经度在前、纬度在后构造的WGS84 LINESTRING，SRID 4326。';
COMMENT ON COLUMN lta.traffic_link.first_seen_time IS '系统第一次从LTA采集到该道路Link的源观察时间。';
COMMENT ON COLUMN lta.traffic_link.last_seen_time IS '系统最近一次仍从LTA看到该道路Link的源观察时间。';
COMMENT ON COLUMN lta.traffic_link.active IS '该道路Link当前是否仍在LTA源数据中有效。';
COMMENT ON COLUMN lta.traffic_link.create_time IS '本条道路Link首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.traffic_link.update_time IS '本条道路Link最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.traffic_link_scope IS 'TrafficSpeedBands道路Link与CIQ研究区域多对多关联白名单，决定哪些Link动态速度允许进入科研数据库。';
COMMENT ON COLUMN lta.traffic_link_scope.uid IS '道路与研究区域关联记录UUID主键。';
COMMENT ON COLUMN lta.traffic_link_scope.link_uid IS '关联lta.traffic_link.uid的UUID外键。';
COMMENT ON COLUMN lta.traffic_link_scope.area_uid IS '关联lta.study_area.uid的UUID外键。';
COMMENT ON COLUMN lta.traffic_link_scope.match_method IS '关联匹配方法：SPATIAL、MANUAL或ROAD_NAME。';
COMMENT ON COLUMN lta.traffic_link_scope.is_primary IS '该研究区域是否为此道路Link的主要归属区域。';
COMMENT ON COLUMN lta.traffic_link_scope.active IS '该白名单关联当前是否生效。';
COMMENT ON COLUMN lta.traffic_link_scope.create_time IS '本条白名单关联首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.traffic_link_scope.update_time IS '本条白名单关联最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.traffic_speed_observation IS 'TrafficSpeedBands动态道路速度时序观测表，每条记录表示标准采集时刻某个道路Link的速度等级。';
COMMENT ON COLUMN lta.traffic_speed_observation.uid IS '道路速度观测UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.traffic_speed_observation.snapshot_time IS '系统标准化后的本轮道路速度快照时间。';
COMMENT ON COLUMN lta.traffic_speed_observation.link_uid IS '关联lta.traffic_link.uid的UUID外键，标识被观测道路Link。';
COMMENT ON COLUMN lta.traffic_speed_observation.speed_band IS 'LTA TrafficSpeedBands返回的速度等级，范围1至8。';
COMMENT ON COLUMN lta.traffic_speed_observation.minimum_speed IS 'LTA返回的该速度等级最小速度，单位按官方接口定义。';
COMMENT ON COLUMN lta.traffic_speed_observation.maximum_speed IS 'LTA返回的该速度等级最大速度，单位按官方接口定义。';
COMMENT ON COLUMN lta.traffic_speed_observation.source_updated_time IS 'LTA源数据更新时间，不等同于入库时间。';
COMMENT ON COLUMN lta.traffic_speed_observation.run_uid IS '关联lta.collection_run.uid的UUID外键，用于追溯本次采集任务。';
COMMENT ON COLUMN lta.traffic_speed_observation.create_time IS '本条速度观测首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.traffic_speed_observation.update_time IS '本条速度观测最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.travel_time_segment IS 'Estimated Travel Times高速公路静态旅行时间分段主表，标准化高速名称、方向、远端终点、起点和终点。';
COMMENT ON COLUMN lta.travel_time_segment.uid IS '旅行时间分段UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.travel_time_segment.name IS 'LTA返回的高速公路名称或简称。';
COMMENT ON COLUMN lta.travel_time_segment.direction IS 'LTA返回的高速公路行驶方向代码。';
COMMENT ON COLUMN lta.travel_time_segment.far_end_point IS 'LTA返回的该方向远端终点文字。';
COMMENT ON COLUMN lta.travel_time_segment.start_point IS 'LTA返回的旅行时间分段起点文字。';
COMMENT ON COLUMN lta.travel_time_segment.end_point IS 'LTA返回的旅行时间分段终点文字。';
COMMENT ON COLUMN lta.travel_time_segment.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域归属。';
COMMENT ON COLUMN lta.travel_time_segment.active IS '该旅行时间分段当前是否仍在LTA源数据中有效。';
COMMENT ON COLUMN lta.travel_time_segment.first_seen_time IS '系统第一次从LTA采集到该分段的源观察时间。';
COMMENT ON COLUMN lta.travel_time_segment.last_seen_time IS '系统最近一次仍从LTA看到该分段的源观察时间。';
COMMENT ON COLUMN lta.travel_time_segment.create_time IS '本条分段首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.travel_time_segment.update_time IS '本条分段最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.travel_time_observation IS '高速公路分段预计旅行时间动态时序表，每条记录表示标准采集时刻某一分段的预计旅行时间。';
COMMENT ON COLUMN lta.travel_time_observation.uid IS '旅行时间观测UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.travel_time_observation.snapshot_time IS '系统标准化后的本轮旅行时间快照时间。';
COMMENT ON COLUMN lta.travel_time_observation.segment_uid IS '关联lta.travel_time_segment.uid的UUID外键。';
COMMENT ON COLUMN lta.travel_time_observation.est_time_min IS 'LTA返回的预计旅行时间，单位为分钟。';
COMMENT ON COLUMN lta.travel_time_observation.run_uid IS '关联lta.collection_run.uid的UUID外键，用于追溯采集任务。';
COMMENT ON COLUMN lta.travel_time_observation.create_time IS '本条旅行时间观测首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.travel_time_observation.update_time IS '本条旅行时间观测最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.traffic_incident_event IS 'LTA实时交通事件生命周期表，保存事件位置与消息，并通过首次发现、最后发现和结束时间实现去重及生命周期管理。';
COMMENT ON COLUMN lta.traffic_incident_event.uid IS '交通事件数据库UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.traffic_incident_event.event_fingerprint IS '由标准化类型、坐标和消息计算的SHA256业务指纹，不作为数据库主键。';
COMMENT ON COLUMN lta.traffic_incident_event.type IS 'LTA返回的交通事件类型。';
COMMENT ON COLUMN lta.traffic_incident_event.latitude IS 'LTA返回的事件纬度，WGS84，NUMERIC(20,16)。';
COMMENT ON COLUMN lta.traffic_incident_event.longitude IS 'LTA返回的事件经度，WGS84，NUMERIC(20,16)。';
COMMENT ON COLUMN lta.traffic_incident_event.geom IS '按经度在前、纬度在后构造的事件WGS84 POINT，SRID 4326。';
COMMENT ON COLUMN lta.traffic_incident_event.message IS 'LTA返回的交通事件描述文本。';
COMMENT ON COLUMN lta.traffic_incident_event.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域。';
COMMENT ON COLUMN lta.traffic_incident_event.first_seen_time IS '系统第一次从LTA采集到该事件状态的时间。';
COMMENT ON COLUMN lta.traffic_incident_event.last_seen_time IS '系统最近一次仍从LTA看到该事件状态的时间。';
COMMENT ON COLUMN lta.traffic_incident_event.resolved_time IS '事件从LTA接口消失或确认结束的时间。';
COMMENT ON COLUMN lta.traffic_incident_event.active IS '该交通事件当前是否仍处于活动状态。';
COMMENT ON COLUMN lta.traffic_incident_event.first_run_uid IS '关联lta.collection_run.uid的UUID外键，记录首次发现该事件的任务。';
COMMENT ON COLUMN lta.traffic_incident_event.last_run_uid IS '关联lta.collection_run.uid的UUID外键，记录最近看到该事件的任务。';
COMMENT ON COLUMN lta.traffic_incident_event.create_time IS '本条交通事件首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.traffic_incident_event.update_time IS '本条交通事件最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.vms_equipment IS 'LTA VMS/EMAS电子信息板设备静态主表，保存EquipmentID及固定位置，不重复保存动态Message。';
COMMENT ON COLUMN lta.vms_equipment.uid IS 'VMS设备数据库UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.vms_equipment.equipment_id IS 'LTA源系统EquipmentID设备业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.vms_equipment.latitude IS 'LTA返回的VMS设备纬度，WGS84，NUMERIC(20,16)。';
COMMENT ON COLUMN lta.vms_equipment.longitude IS 'LTA返回的VMS设备经度，WGS84，NUMERIC(20,16)。';
COMMENT ON COLUMN lta.vms_equipment.geom IS '按经度在前、纬度在后构造的设备WGS84 POINT，SRID 4326。';
COMMENT ON COLUMN lta.vms_equipment.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域。';
COMMENT ON COLUMN lta.vms_equipment.first_seen_time IS '系统第一次从LTA采集到该VMS设备的时间。';
COMMENT ON COLUMN lta.vms_equipment.last_seen_time IS '系统最近一次仍从LTA看到该VMS设备的时间。';
COMMENT ON COLUMN lta.vms_equipment.active IS '该VMS设备当前是否仍在LTA源数据中有效。';
COMMENT ON COLUMN lta.vms_equipment.create_time IS '本条VMS设备首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.vms_equipment.update_time IS '本条VMS设备最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.vms_message_state IS 'VMS电子信息板文本状态生命周期表，相同消息更新last_seen_time，消息改变时结束旧状态并创建新UUID记录。';
COMMENT ON COLUMN lta.vms_message_state.uid IS 'VMS消息状态UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.vms_message_state.equipment_uid IS '关联lta.vms_equipment.uid的UUID外键，标识显示消息的设备。';
COMMENT ON COLUMN lta.vms_message_state.message IS 'LTA VMS接口返回的当前显示文本。';
COMMENT ON COLUMN lta.vms_message_state.message_hash IS '标准化VMS消息文本的SHA256，用于识别状态变化。';
COMMENT ON COLUMN lta.vms_message_state.first_seen_time IS '系统第一次采集到该消息状态的时间。';
COMMENT ON COLUMN lta.vms_message_state.last_seen_time IS '系统最近一次仍看到相同消息状态的时间。';
COMMENT ON COLUMN lta.vms_message_state.ended_time IS '该消息被新消息替代或消失的时间。';
COMMENT ON COLUMN lta.vms_message_state.active IS '该消息状态当前是否仍在设备上显示。';
COMMENT ON COLUMN lta.vms_message_state.first_run_uid IS '关联lta.collection_run.uid的UUID外键，记录首次发现该消息的任务。';
COMMENT ON COLUMN lta.vms_message_state.last_run_uid IS '关联lta.collection_run.uid的UUID外键，记录最近看到该消息的任务。';
COMMENT ON COLUMN lta.vms_message_state.create_time IS '本条VMS消息状态首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.vms_message_state.update_time IS '本条VMS消息状态最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.faulty_traffic_light_event IS 'LTA故障交通信号灯生命周期表，以AlarmID为源系统业务编号，以uid为数据库UUID主键。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.uid IS '故障交通灯事件UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.alarm_id IS 'LTA源系统AlarmID故障业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.node_id IS 'LTA源系统NodeID节点业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.fault_type IS 'LTA返回的故障类型代码，不限制为当前已知代码。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.source_start_time IS 'LTA源系统提供的故障开始时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.source_end_time IS 'LTA源系统提供的故障结束时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.message IS 'LTA返回的故障描述文本。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.first_seen_time IS '系统第一次采集到该故障事件的时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.last_seen_time IS '系统最近一次仍看到该故障事件的时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.resolved_time IS '故障事件从接口消失或确认解决的时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.active IS '该故障事件当前是否仍处于活动状态。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.first_run_uid IS '关联lta.collection_run.uid的UUID外键，记录首次发现任务。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.last_run_uid IS '关联lta.collection_run.uid的UUID外键，记录最近发现任务。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.create_time IS '本条故障事件首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.faulty_traffic_light_event.update_time IS '本条故障事件最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.road_work_event IS 'LTA Approved Road Works道路施工事件生命周期表，记录施工计划、道路及事件出现和结束过程。';
COMMENT ON COLUMN lta.road_work_event.uid IS '道路施工事件UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.road_work_event.event_id IS 'LTA源系统道路施工EventID业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.road_work_event.start_date IS 'LTA源数据提供的施工开始日期，仅表示日期。';
COMMENT ON COLUMN lta.road_work_event.end_date IS 'LTA源数据提供的施工结束日期，仅表示日期。';
COMMENT ON COLUMN lta.road_work_event.svc_dept IS 'LTA返回的施工负责服务部门。';
COMMENT ON COLUMN lta.road_work_event.road_name IS 'LTA返回的施工道路名称。';
COMMENT ON COLUMN lta.road_work_event.other IS 'LTA返回的道路施工其他说明。';
COMMENT ON COLUMN lta.road_work_event.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域。';
COMMENT ON COLUMN lta.road_work_event.first_seen_time IS '系统第一次采集到该施工事件的时间。';
COMMENT ON COLUMN lta.road_work_event.last_seen_time IS '系统最近一次仍看到该施工事件的时间。';
COMMENT ON COLUMN lta.road_work_event.resolved_time IS '施工事件从接口消失或确认结束的时间。';
COMMENT ON COLUMN lta.road_work_event.active IS '该道路施工事件当前是否仍处于活动状态。';
COMMENT ON COLUMN lta.road_work_event.first_run_uid IS '关联lta.collection_run.uid的UUID外键，记录首次发现任务。';
COMMENT ON COLUMN lta.road_work_event.last_run_uid IS '关联lta.collection_run.uid的UUID外键，记录最近发现任务。';
COMMENT ON COLUMN lta.road_work_event.create_time IS '本条道路施工事件首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.road_work_event.update_time IS '本条道路施工事件最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.traffic_flow_file IS 'Traffic Flow历史交通流量下载文件月度登记表，每月最后一天获取临时下载链接并登记实际文件及审计信息。';
COMMENT ON COLUMN lta.traffic_flow_file.uid IS '交通流量文件登记UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.traffic_flow_file.check_month IS '月度检查所属月份，统一存该月第一天，例如2026-08-01。';
COMMENT ON COLUMN lta.traffic_flow_file.run_uid IS '关联lta.collection_run.uid的UUID外键，表示获取和下载该文件的任务。';
COMMENT ON COLUMN lta.traffic_flow_file.download_url IS 'LTA Traffic Flow接口返回的临时实际文件下载URL。';
COMMENT ON COLUMN lta.traffic_flow_file.file_name IS '已下载交通流量文件名称。';
COMMENT ON COLUMN lta.traffic_flow_file.file_path IS '已下载交通流量文件在外部文件系统中的路径。';
COMMENT ON COLUMN lta.traffic_flow_file.file_size_bytes IS '已下载交通流量文件大小，单位字节。';
COMMENT ON COLUMN lta.traffic_flow_file.sha256 IS '已下载文件内容SHA256校验值，用于版本与完整性审计。';
COMMENT ON COLUMN lta.traffic_flow_file.is_new_version IS '本月下载文件相对历史登记是否为新版本。';
COMMENT ON COLUMN lta.traffic_flow_file.source_period IS 'LTA下载文件声明的数据覆盖时期。';
COMMENT ON COLUMN lta.traffic_flow_file.downloaded_time IS '实际完成文件下载的时间。';
COMMENT ON COLUMN lta.traffic_flow_file.parse_status IS '文件解析状态：NOT_PARSED、PARSED或FAILED。';
COMMENT ON COLUMN lta.traffic_flow_file.parse_message IS '文件解析结果摘要或失败原因。';
COMMENT ON COLUMN lta.traffic_flow_file.create_time IS '本条文件登记首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.traffic_flow_file.update_time IS '本条文件登记最近一次UPDATE时间，由数据库触发器自动维护。';

COMMENT ON TABLE lta.road_opening_event IS 'LTA Planned Road Openings计划道路开放事件生命周期表，记录未来道路开放及道路网络调整。';
COMMENT ON COLUMN lta.road_opening_event.uid IS '计划道路开放事件UUID主键，由PostgreSQL自动生成。';
COMMENT ON COLUMN lta.road_opening_event.event_id IS 'LTA源系统道路开放EventID业务编号，不作为数据库主键或外键。';
COMMENT ON COLUMN lta.road_opening_event.start_date IS 'LTA源数据提供的计划道路开放开始日期，仅表示日期。';
COMMENT ON COLUMN lta.road_opening_event.end_date IS 'LTA源数据提供的计划道路开放结束日期，仅表示日期。';
COMMENT ON COLUMN lta.road_opening_event.svc_dept IS 'LTA返回的道路开放负责服务部门。';
COMMENT ON COLUMN lta.road_opening_event.road_name IS 'LTA返回的计划开放道路名称。';
COMMENT ON COLUMN lta.road_opening_event.other IS 'LTA返回的计划道路开放其他说明。';
COMMENT ON COLUMN lta.road_opening_event.area_uid IS '可空UUID外键，关联lta.study_area.uid表示CIQ研究区域。';
COMMENT ON COLUMN lta.road_opening_event.first_seen_time IS '系统第一次采集到该道路开放事件的时间。';
COMMENT ON COLUMN lta.road_opening_event.last_seen_time IS '系统最近一次仍看到该道路开放事件的时间。';
COMMENT ON COLUMN lta.road_opening_event.resolved_time IS '道路开放事件从接口消失或确认结束的时间。';
COMMENT ON COLUMN lta.road_opening_event.active IS '该计划道路开放事件当前是否仍处于活动状态。';
COMMENT ON COLUMN lta.road_opening_event.first_run_uid IS '关联lta.collection_run.uid的UUID外键，记录首次发现任务。';
COMMENT ON COLUMN lta.road_opening_event.last_run_uid IS '关联lta.collection_run.uid的UUID外键，记录最近发现任务。';
COMMENT ON COLUMN lta.road_opening_event.create_time IS '本条道路开放事件首次INSERT进入PostgreSQL的入库时间。';
COMMENT ON COLUMN lta.road_opening_event.update_time IS '本条道路开放事件最近一次UPDATE时间，由数据库触发器自动维护。';
