<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import L from 'leaflet'
import { useI18n } from 'vue-i18n'
import type { RouteShape, RouteTrace, Vehicle } from '../../api/dashboardApi'
import type { CityConfig } from '../../config/cities'

const props=defineProps<{city:CityConfig; vehicles:Vehicle[]; routeTraces:RouteTrace[]; roadShapes:RouteShape[]; selectedRoute?:string; showAllRoutes:boolean; loading:boolean; error?:string; updatedAt?:string}>()
const emit=defineEmits<{retry:[];'route-change':[route:string];'toggle-all-routes':[]}>()
const {t,locale}=useI18n();const root=ref<HTMLElement>();const mapEl=ref<HTMLElement>();let map:L.Map|undefined;let routeLayer:L.LayerGroup|undefined;let historyLayer:L.LayerGroup|undefined;let vehicleLayer:L.LayerGroup|undefined
const full=ref(false)
const routeOptions=computed(()=>{const values=new Map<string,string>();for(const v of props.vehicles){const key=v.routeShortName||v.resolvedRouteId;if(key&&Number(v.freshnessSeconds??999999)<=600)values.set(key,v.routeLongName?`${key} · ${v.routeLongName}`:key)}return [...values].sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true}))})
const focusedVehicles=computed(()=>props.vehicles.filter(v=>Number(v.freshnessSeconds??999999)<=600&&(props.showAllRoutes||(v.routeShortName||v.resolvedRouteId)===props.selectedRoute)))
const activeCount=computed(()=>focusedVehicles.value.length)
const activeRouteCount=computed(()=>new Set([...props.roadShapes.map(shape=>shape.routeKey),...props.routeTraces.map(trace=>trace.routeKey)]).size)

function routeColor(route?:string){const palette=['#00d9ff','#14e6a2','#f9b33d','#a97bff','#ff667d','#3f8cff'];let h=0;for(const c of route||'--')h=((h<<5)-h+c.charCodeAt(0))|0;return palette[Math.abs(h)%palette.length]}
function esc(v:unknown){return String(v??'--').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
function popup(v:Vehicle){const row=(label:string,value:unknown)=>`<div class="popup-row"><span>${esc(label)}</span><b>${esc(value)}</b></div>`;return `<div class="vehicle-popup"><h3>${esc(t('vehicleInfo'))}<em>${esc(v.routeShortName||v.resolvedRouteId||'--')}</em></h3>${row(t('city'),v.cityName)}${row(t('vehicleId'),v.vehicleId)}${row(t('vehicleLabel'),v.vehicleLabel)}${row(t('licensePlate'),v.licensePlate)}${row(t('route'),v.routeShortName||v.resolvedRouteId)}${row(t('routeName'),v.routeLongName)}${row(t('tripId'),v.tripId)}${row(t('direction'),v.directionId)}${row(t('latitude'),v.latitude?.toFixed(6))}${row(t('longitude'),v.longitude?.toFixed(6))}${row(t('speed'),v.speedKmh==null?'--':v.speedKmh.toFixed(1)+' km/h')}${row(t('vehicleTime'),format(v.vehicleTime))}${row(t('lastSeen'),format(v.lastSeenTime))}${row(t('freshness'),v.freshnessSeconds==null?'--':v.freshnessSeconds+' s')}${row(t('qc'),v.qcFlags?.length?v.qcFlags.join(', '):'NORMAL')}</div>`}
function format(value?:string){return value?new Intl.DateTimeFormat(locale.value==='zh'?'zh-CN':'en-GB',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'short',timeStyle:'medium'}).format(new Date(value)):'--'}
function latestByDirection(){const result=new Map<string,Vehicle>();for(const v of focusedVehicles.value){const route=v.routeShortName||v.resolvedRouteId||'--';const key=`${route}\u0000${v.directionId??'unknown'}`,current=result.get(key);const time=Date.parse(v.vehicleTime||v.lastSeenTime||'');const currentTime=current?Date.parse(current.vehicleTime||current.lastSeenTime||''):0;if(!current||time>currentTime)result.set(key,v)}return new Set([...result.values()].map(v=>v.vehicleId))}
function busIcon(color:string,direction?:number,compact=false){const size=compact?26:34,anchor=size/2;return L.divIcon({className:`route-bus-icon${compact?' compact':''}`,iconSize:[size,size],iconAnchor:[anchor,anchor],popupAnchor:[0,-anchor],html:`<svg viewBox="0 0 36 36" role="img" aria-label="${esc(t('latestDirectionVehicle'))}"><circle cx="18" cy="18" r="17" fill="#041426" stroke="${color}" stroke-width="2"/><rect x="9" y="8" width="18" height="20" rx="5" fill="${color}"/><rect x="12" y="11" width="12" height="7" rx="2" fill="#06203a"/><path d="M12 22h12" stroke="#e9fbff" stroke-width="2"/><circle cx="13" cy="29" r="2.5" fill="#e9fbff"/><circle cx="23" cy="29" r="2.5" fill="#e9fbff"/><text x="18" y="17" text-anchor="middle" font-size="7" font-weight="700" fill="#e9fbff">${direction??'?'}</text></svg>`})}
function addHitTarget(v:Vehicle,point:L.LatLngTuple,color:string){const hit=L.circleMarker(point,{renderer:(map as any)._renderer,radius:16,stroke:false,fill:true,fillColor:color,fillOpacity:.01,bubblingMouseEvents:false}).bindPopup(popup(v),{maxWidth:340}).bindTooltip(`${v.routeShortName||v.resolvedRouteId||'--'} · ${v.vehicleId}`,{direction:'top',offset:[0,-15],opacity:.94});hit.on('mouseover',()=>{if(mapEl.value)mapEl.value.style.cursor='pointer';hit.setStyle({fillOpacity:.18})});hit.on('mouseout',()=>{if(mapEl.value)mapEl.value.style.cursor='';hit.setStyle({fillOpacity:.01})});hit.addTo(vehicleLayer!)}
function addHistoryPoint(trace:RouteTrace,latitude:number,longitude:number,vehicleTime?:string){const color=routeColor(trace.routeKey),point:L.LatLngTuple=[latitude,longitude],label=`${trace.routeKey} · ${trace.vehicleId} · ${format(vehicleTime)}`;const hit=L.circleMarker(point,{renderer:(map as any)._renderer,radius:11,stroke:false,fill:true,fillColor:color,fillOpacity:.01,bubblingMouseEvents:false}).bindTooltip(label,{direction:'top',opacity:.94});hit.on('mouseover',()=>hit.setStyle({fillOpacity:.2}));hit.on('mouseout',()=>hit.setStyle({fillOpacity:.01}));hit.addTo(historyLayer!);L.circleMarker(point,{renderer:(map as any)._renderer,radius:4.5,color:'#e9fcff',weight:1.2,fillColor:color,fillOpacity:.92,interactive:false}).addTo(historyLayer!)}
function render(fit=false){if(!map||!routeLayer||!historyLayer||!vehicleLayer)return;routeLayer.clearLayers();historyLayer.clearLayers();vehicleLayer.clearLayers();const bounds:L.LatLngTuple[]=[]
  for(const shape of props.roadShapes){const color=routeColor(shape.routeKey);const points=shape.points.filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)).map(p=>[p.latitude,p.longitude] as L.LatLngTuple);if(points.length<2)continue;bounds.push(...points);L.polyline(points,{color:'#00111f',weight:props.showAllRoutes?11:9,opacity:.92,smoothFactor:.3,lineCap:'round',lineJoin:'round',interactive:false}).addTo(routeLayer);L.polyline(points,{color,weight:props.showAllRoutes?5.5:4.5,opacity:1,smoothFactor:.3,lineCap:'round',lineJoin:'round'}).bindTooltip(`${shape.routeKey} · ${t('gtfsRoadRoute')} · ${t('direction')} ${shape.directionId??'--'}`,{sticky:true}).addTo(routeLayer)}
  if(props.showAllRoutes){const fallback=new Map<string,RouteTrace>();for(const trace of props.routeTraces){const key=`${trace.routeKey}\u0000${trace.directionId??'x'}`,current=fallback.get(key);if(!current||trace.points.length>current.points.length)fallback.set(key,trace)}for(const trace of fallback.values()){const color=routeColor(trace.routeKey),points=trace.points.filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)).map(p=>[p.latitude,p.longitude] as L.LatLngTuple);if(points.length<2)continue;bounds.push(...points);L.polyline(points,{color:'#00111f',weight:11,opacity:.92,smoothFactor:.55,lineCap:'round',lineJoin:'round',interactive:false}).addTo(routeLayer);L.polyline(points,{color,weight:5.5,opacity:1,smoothFactor:.55,lineCap:'round',lineJoin:'round'}).bindTooltip(`${trace.routeKey} · ${t('gpsFallbackRoute')} · ${t('direction')} ${trace.directionId??'--'}`,{sticky:true}).addTo(routeLayer);for(const p of trace.points)if(Number.isFinite(p.latitude)&&Number.isFinite(p.longitude))addHistoryPoint(trace,p.latitude,p.longitude,p.vehicleTime)}}else{for(const trace of props.routeTraces)for(const p of trace.points){if(!Number.isFinite(p.latitude)||!Number.isFinite(p.longitude))continue;addHistoryPoint(trace,p.latitude,p.longitude,p.vehicleTime)}}
  const latestIds=latestByDirection();for(const v of focusedVehicles.value){if(!Number.isFinite(v.latitude)||!Number.isFinite(v.longitude)||v.latitude < -90||v.latitude > 90||v.longitude < -180||v.longitude > 180||(v.latitude===0&&v.longitude===0))continue;const color=routeColor(v.routeShortName||v.resolvedRouteId),point:L.LatLngTuple=[v.latitude,v.longitude];addHitTarget(v,point,color);if(latestIds.has(v.vehicleId)){const compact=props.showAllRoutes;L.marker(point,{icon:busIcon(color,v.directionId,compact),zIndexOffset:compact?700:1000,interactive:true}).bindPopup(popup(v),{maxWidth:340}).bindTooltip(`${v.routeShortName||v.resolvedRouteId||'--'} · ${t('direction')} ${v.directionId??'--'} · ${t('latestPosition')}`,{direction:'top',offset:[0,compact?-13:-17],opacity:.96}).addTo(vehicleLayer)}else{L.circleMarker(point,{renderer:(map as any)._renderer,radius:props.showAllRoutes?5.5:7,color:'#e9fcff',weight:1.4,fillColor:color,fillOpacity:1,interactive:false}).addTo(vehicleLayer)}}
  if(fit&&bounds.length)map.fitBounds(L.latLngBounds(bounds),{padding:[28,28],maxZoom:14})
}
async function toggleFullscreen(){if(!root.value)return;if(!document.fullscreenElement)await root.value.requestFullscreen();else await document.exitFullscreen()}
function onFullscreen(){full.value=!!document.fullscreenElement;setTimeout(()=>map?.invalidateSize(),100)}
onMounted(()=>{map=L.map(mapEl.value!,{preferCanvas:true,zoomControl:true,attributionControl:true}).setView([props.city.latitude,props.city.longitude],props.city.zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);routeLayer=L.layerGroup().addTo(map);historyLayer=L.layerGroup().addTo(map);vehicleLayer=L.layerGroup().addTo(map);render(true);document.addEventListener('fullscreenchange',onFullscreen)})
onBeforeUnmount(()=>{document.removeEventListener('fullscreenchange',onFullscreen);map?.remove()})
watch(()=>props.city,async city=>{map?.setView([city.latitude,city.longitude],city.zoom);await nextTick();map?.invalidateSize()});watch(()=>props.vehicles,()=>render(),{deep:false});watch(()=>props.routeTraces,()=>render(),{deep:false});watch(()=>props.roadShapes,()=>render(true),{deep:false});watch(locale,()=>render())
</script>
<template><div ref="root" class="map-shell"><div ref="mapEl" class="map-canvas"></div><div class="route-focus"><div class="route-focus-row"><label>{{t('focusedRoute')}}</label><select :value="selectedRoute" @change="emit('route-change',($event.target as HTMLSelectElement).value)"><option v-for="[key,label] in routeOptions" :key="key" :value="key">{{label}}</option></select></div><button class="all-routes-btn" :class="{active:showAllRoutes}" @click="emit('toggle-all-routes')">{{showAllRoutes?t('backToSingleRoute'):t('showAllRoutes')}}</button></div><button class="fullscreen-btn" @click="toggleFullscreen">⛶ {{full?t('exitFullScreen'):t('fullScreen')}}</button><div v-if="loading" class="panel-state">{{t('loading')}}</div><div v-else-if="error" class="panel-state error">{{t('unavailable')}}<button @click="emit('retry')">{{t('retry')}}</button></div><footer class="map-footer"><span>◉ {{showAllRoutes?t('allRoutesHint'):t('singleRouteHint')}}</span><span>{{t('activeRoutes')}}: <b>{{activeRouteCount.toLocaleString()}}</b></span><span>{{t('routeVehicles')}}: <b>{{activeCount.toLocaleString()}}</b></span><span>{{t('lastUpdated')}}: <b>{{format(updatedAt)}}</b></span></footer></div></template>
