import axios from 'axios'

export interface CiqOverview { plannedTasks:number;executedTasks:number;successfulTasks:number;failedTasks:number;successRate?:number;generatedAt:string }
export interface CiqApiStatus {apiCode:string;apiName:string;nameZh:string;endpoint:string;schedule:string;status:string;lastRequest?:string;lastSuccess?:string;lastSuccessTime?:string;latestDataTime?:string;todayCount?:number;totalCount?:number;httpStatus?:number;rawRecords?:number;ciqSelected?:number;dbInserted?:number;todayExecutions:number;completeness:string;retryCount?:number;pages?:number;responseBytes?:number;durationMs?:number;lastError?:string;rawFile?:string;fileSizeBytes?:number;sha256?:string;metrics:Record<string,string|number|null>}
export interface CiqTrendPoint {apiCode:string;bucketTime:string;executions:number;records:number}
export interface CiqAuditCell {text:string;status:string}
export interface CiqAuditRow {code:string;itemEn:string;itemZh:string;apis:Record<string,CiqAuditCell>}
export interface CiqRequestLog {time:string;apiCode:string;apiName:string;httpStatus?:number;rawRecords?:number;ciqSelected?:number;inserted?:number;durationMs?:number;retry?:number;archive:string;status:string}
export interface CiqStorage {rawTodayFiles:number;rawTotalFiles:number;rawTodayBytes:number;rawTotalBytes:number;archiveCount:number;latestArchive?:string;archiveStatus:string;dbTodayInserted:number;dbTotalRows:number;latestDbInsert?:string;dbStatus:string;diskTotalBytes?:number;diskUsedBytes?:number;diskFreeBytes?:number;diskUsagePercent?:number;generatedAt:string}
export interface CiqMapPoint {apiCode:'API01'|'API02';recordId:string;title:string;category:string;latitude:number;longitude:number;observedAt?:string;details:Record<string,string|number|null>}
export interface CiqDataRecord {apiCode:string;recordId:string;category:string;title:string;description:string;eventTime?:string;status:string;latitude?:number;longitude?:number;details:Record<string,string|number|null>}
const http=axios.create({baseURL:'/api/ciq/dashboard',timeout:30000})
export const ciqDashboardApi={overview:()=>http.get<CiqOverview>('/overview').then(r=>r.data),apis:()=>http.get<CiqApiStatus[]>('/apis').then(r=>r.data),trend:(hours=3)=>http.get<CiqTrendPoint[]>('/trend',{params:{hours}}).then(r=>r.data),audit:()=>http.get<CiqAuditRow[]>('/audit').then(r=>r.data),requests:()=>http.get<CiqRequestLog[]>('/requests/recent').then(r=>r.data),storage:()=>http.get<CiqStorage>('/storage').then(r=>r.data),detail:(code:string)=>http.get<CiqApiStatus>(`/api/${code}`).then(r=>r.data),mapPoints:(api='ALL',limit=1200)=>http.get<CiqMapPoint[]>('/map-points',{params:{api,limit}}).then(r=>r.data),dataRecords:(params:{api?:string;from?:string;to?:string;category?:string;limit?:number})=>http.get<CiqDataRecord[]>('/data/latest',{params}).then(r=>r.data)}
