import type { Acquisition, ApiRequest, Availability, Anomaly, Overview, RouteShape, RouteTrace, RouteTracesResponse, SystemStatus, TrendPoint, Vehicle, VehiclesResponse } from '../dashboardApi'

type Json = Record<string, any>
const pick=(v:Json,...keys:string[])=>keys.map(k=>v?.[k]).find(x=>x!==undefined&&x!==null)
const num=(v:unknown)=>v===null||v===undefined||v===''?undefined:Number(v)
const validPoint=(lat:unknown,lon:unknown)=>{const a=num(lat),b=num(lon);return a!==undefined&&b!==undefined&&Number.isFinite(a)&&Number.isFinite(b)&&a>=-90&&a<=90&&b>=-180&&b<=180&&!(a===0&&b===0)?[a,b] as const:undefined}

export function adaptVehicle(v:Json):Vehicle|null {
  const point=validPoint(pick(v,'latitude','lat'),pick(v,'longitude','lng','lon')); if(!point)return null
  return {cityCode:pick(v,'cityCode','city_code')??'',cityName:pick(v,'cityName','city_name')??'',vehicleId:pick(v,'vehicleId','vehicle_id')??'--',vehicleLabel:pick(v,'vehicleLabel','vehicle_label'),licensePlate:pick(v,'licensePlate','license_plate'),tripId:pick(v,'tripId','trip_id'),resolvedRouteId:pick(v,'resolvedRouteId','resolved_route_id'),routeShortName:pick(v,'routeShortName','route_short_name'),routeLongName:pick(v,'routeLongName','route_long_name'),directionId:num(pick(v,'directionId','direction_id')),latitude:point[0],longitude:point[1],speedKmh:num(pick(v,'speedKmh','speed_kmh','speed')),vehicleTime:pick(v,'vehicleTime','vehicle_time'),lastSeenTime:pick(v,'lastSeenTime','last_seen_time'),freshnessSeconds:num(pick(v,'freshnessSeconds','freshness_seconds')),qcFlags:pick(v,'qcFlags','qc_flags')??[]}
}
export function adaptVehicles(raw:Json):VehiclesResponse {const vehicles=(pick(raw,'vehicles','data')??[]).map(adaptVehicle).filter(Boolean) as Vehicle[];return {cityCode:pick(raw,'cityCode','city_code')??'',generatedAt:pick(raw,'generatedAt','generated_at')??new Date().toISOString(),count:vehicles.length,vehicles}}
const point=(v:Json)=>{const p=validPoint(pick(v,'latitude','lat'),pick(v,'longitude','lng','lon'));return p?{latitude:p[0],longitude:p[1],vehicleTime:pick(v,'vehicleTime','vehicle_time')}:null}
export function adaptRouteTraces(raw:Json):RouteTracesResponse {const shapes:RouteShape[]=(pick(raw,'roadShapes','road_shapes')??[]).map((s:Json)=>({routeKey:pick(s,'routeKey','route_key')??'',directionId:num(pick(s,'directionId','direction_id')),shapeId:pick(s,'shapeId','shape_id')??'',points:(s.points??[]).map(point).filter(Boolean)}));const traces:RouteTrace[]=(raw.traces??[]).map((s:Json)=>({routeKey:pick(s,'routeKey','route_key')??'',routeShortName:pick(s,'routeShortName','route_short_name'),routeLongName:pick(s,'routeLongName','route_long_name'),vehicleId:pick(s,'vehicleId','vehicle_id')??'',directionId:num(pick(s,'directionId','direction_id')),points:(s.points??[]).map(point).filter(Boolean)}));return {cityCode:pick(raw,'cityCode','city_code')??'',generatedAt:pick(raw,'generatedAt','generated_at')??new Date().toISOString(),selectedRouteKey:pick(raw,'selectedRouteKey','selected_route_key'),selectedRouteShortName:pick(raw,'selectedRouteShortName','selected_route_short_name'),selectedRouteLongName:pick(raw,'selectedRouteLongName','selected_route_long_name'),routeCount:num(pick(raw,'routeCount','route_count'))??0,segmentCount:num(pick(raw,'segmentCount','segment_count'))??0,historyWindowMinutes:num(pick(raw,'historyWindowMinutes','history_window_minutes'))??0,roadShapes:shapes,traces}}

export const adaptAcquisition=(rows:Json[]):Acquisition[]=>rows.map(v=>({cityCode:pick(v,'cityCode','city_code')??'',cityName:pick(v,'cityName','city_name')??'',latestRequest:pick(v,'latestRequest','latest_request'),apiStatus:pick(v,'apiStatus','api_status')??'UNKNOWN',todayRecords:num(pick(v,'todayRecords','today_records'))??0,yesterdayRecords:num(pick(v,'yesterdayRecords','yesterday_records'))??0,insertedRecords:num(pick(v,'insertedRecords','inserted_records'))??0,anomalies:num(v.anomalies)??0,requestCount:num(pick(v,'requestCount','request_count'))??0,successfulRequests:num(pick(v,'successfulRequests','successful_requests'))??0}))
export const adaptTrend=(rows:Json[]):TrendPoint[]=>rows.map(v=>({cityCode:pick(v,'cityCode','city_code')??'',bucketTime:pick(v,'bucketTime','bucket_time')??'',recordCount:num(pick(v,'recordCount','record_count'))??0}))
export const adaptOverview=(v:Json):Overview=>({activeVehicles:num(pick(v,'activeVehicles','active_vehicles'))??0,todayRecords:num(pick(v,'todayRecords','today_records'))??0,yesterdayRecords:num(pick(v,'yesterdayRecords','yesterday_records'))??0,totalRecords:num(pick(v,'totalRecords','total_records'))??0,totalRecordsEstimated:Boolean(pick(v,'totalRecordsEstimated','total_records_estimated')),latestGpsUpdate:pick(v,'latestGpsUpdate','latest_gps_update'),abnormalVehicles:num(pick(v,'abnormalVehicles','abnormal_vehicles'))??0,apiSuccessRate:num(pick(v,'apiSuccessRate','api_success_rate')),activeVehiclesDefinition:pick(v,'activeVehiclesDefinition','active_vehicles_definition')??'',abnormalVehiclesDefinition:pick(v,'abnormalVehiclesDefinition','abnormal_vehicles_definition')??'',generatedAt:pick(v,'generatedAt','generated_at')??new Date().toISOString()})
export const adaptAvailability=<T>(v:Json):Availability<T>=>({available:Boolean(v.available),data:v.data,message:v.message})
export const adaptAnomalies=(v:Json):Availability<Anomaly[]>=>adaptAvailability(v)
export const adaptRequests=(v:Json):Availability<ApiRequest[]>=>adaptAvailability(v)
export const adaptStatus=(v:Json):SystemStatus=>v as SystemStatus
