\set ON_ERROR_STOP on
BEGIN;
CREATE TABLE IF NOT EXISTS kl.api_request_log        (LIKE jb.api_request_log        INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.realtime_snapshot      (LIKE jb.realtime_snapshot      INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_route           (LIKE jb.static_route           INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_shape           (LIKE jb.static_shape           INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_shape_point     (LIKE jb.static_shape_point     INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_stop            (LIKE jb.static_stop            INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_stop_time       (LIKE jb.static_stop_time       INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_trip            (LIKE jb.static_trip            INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.static_version         (LIKE jb.static_version         INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.vehicle_latest_state   (LIKE jb.vehicle_latest_state   INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.vehicle_observation    (LIKE jb.vehicle_observation    INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
CREATE TABLE IF NOT EXISTS kl.vehicle_observation_qc (LIKE jb.vehicle_observation_qc INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMPRESSION);
COMMIT;

