package com.mytransitgps.modules.ciq.config;
import com.fasterxml.jackson.databind.ObjectMapper;import com.mytransitgps.modules.ciq.client.*;import com.mytransitgps.modules.ciq.collector.*;import com.mytransitgps.modules.ciq.parser.*;import com.mytransitgps.modules.ciq.persistence.*;import com.mytransitgps.modules.ciq.quality.*;import com.mytransitgps.modules.ciq.scheduler.*;import com.mytransitgps.modules.ciq.storage.CiqJsonStorageService;import com.mytransitgps.platform.collection.CollectionExecutor;import com.mytransitgps.platform.http.TrafficHttpClient;import org.springframework.beans.factory.ObjectProvider;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.context.annotation.*;
/** CIQ 八接口 Bean 装配。 */
@Configuration(proxyBeanMethods=false) @ConditionalOnProperty(prefix="traffic.ciq",name="enabled",havingValue="true")
public class CiqModuleConfiguration {
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-speed",name="enabled",havingValue="true") LtaTrafficSpeedClient api01Client(TrafficHttpClient h,CiqProperties p){return new LtaTrafficSpeedClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-speed",name="enabled",havingValue="true") CiqTrafficSpeedCollector api01Collector(LtaTrafficSpeedClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<CiqTrafficSpeedPersistenceService> ps){return new CiqTrafficSpeedCollector(c,p,s,m,new TrafficSpeedBandsParser(m),new CiqTrafficSpeedValidator(),ps.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.estimated-travel-times",name="enabled",havingValue="true") LtaEstimatedTravelTimesClient api02Client(TrafficHttpClient h,CiqProperties p){return new LtaEstimatedTravelTimesClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.estimated-travel-times",name="enabled",havingValue="true") CiqEstimatedTravelTimesCollector api02Collector(LtaEstimatedTravelTimesClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<EstimatedTravelTimesPersistenceService> ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqEstimatedTravelTimesCollector(c,p,s,new EstimatedTravelTimesParser(m),new EstimatedTravelTimesValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-incidents",name="enabled",havingValue="true") LtaTrafficIncidentsClient api03Client(TrafficHttpClient h,CiqProperties p){return new LtaTrafficIncidentsClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-incidents",name="enabled",havingValue="true") CiqTrafficIncidentsCollector api03Collector(LtaTrafficIncidentsClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<TrafficIncidentsPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqTrafficIncidentsCollector(c,p,s,new TrafficIncidentsParser(m),new TrafficIncidentsValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.vms",name="enabled",havingValue="true") LtaVmsClient api04Client(TrafficHttpClient h,CiqProperties p){return new LtaVmsClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.vms",name="enabled",havingValue="true") CiqVmsCollector api04Collector(LtaVmsClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<VmsPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqVmsCollector(c,p,s,new VmsParser(m),new VmsValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.faulty-traffic-lights",name="enabled",havingValue="true") LtaFaultyTrafficLightsClient api05Client(TrafficHttpClient h,CiqProperties p){return new LtaFaultyTrafficLightsClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.faulty-traffic-lights",name="enabled",havingValue="true") CiqFaultyTrafficLightsCollector api05Collector(LtaFaultyTrafficLightsClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<FaultyTrafficLightsPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqFaultyTrafficLightsCollector(c,p,s,new FaultyTrafficLightsParser(m),new FaultyTrafficLightsValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.road-works",name="enabled",havingValue="true") LtaRoadWorksClient api06Client(TrafficHttpClient h,CiqProperties p){return new LtaRoadWorksClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.road-works",name="enabled",havingValue="true") CiqRoadWorksCollector api06Collector(LtaRoadWorksClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<RoadWorksPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqRoadWorksCollector(c,p,s,new RoadWorksParser(m),new RoadWorksValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-flow",name="enabled",havingValue="true") LtaTrafficFlowClient api07Client(TrafficHttpClient h,CiqProperties p){return new LtaTrafficFlowClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.traffic-flow",name="enabled",havingValue="true") CiqTrafficFlowCollector api07Collector(LtaTrafficFlowClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<TrafficFlowPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqTrafficFlowCollector(c,p,s,new TrafficFlowParser(m),new TrafficFlowValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.road-openings",name="enabled",havingValue="true") LtaRoadOpeningsClient api08Client(TrafficHttpClient h,CiqProperties p){return new LtaRoadOpeningsClient(h,p);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.collectors.road-openings",name="enabled",havingValue="true") CiqRoadOpeningsCollector api08Collector(LtaRoadOpeningsClient c,CiqProperties p,CiqJsonStorageService s,ObjectMapper m,ObjectProvider<RoadOpeningsPersistenceService>ps,ObjectProvider<CiqAuditPersistenceService>a){return new CiqRoadOpeningsCollector(c,p,s,new RoadOpeningsParser(m),new RoadOpeningsValidator(),ps.getIfAvailable(),a.getIfAvailable());}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqCollectionScheduler api01Scheduler(CollectionExecutor e,ObjectProvider<CiqTrafficSpeedCollector>c){return new CiqCollectionScheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi02Scheduler api02Scheduler(CollectionExecutor e,ObjectProvider<CiqEstimatedTravelTimesCollector>c){return new CiqApi02Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi03Scheduler api03Scheduler(CollectionExecutor e,ObjectProvider<CiqTrafficIncidentsCollector>c){return new CiqApi03Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi04Scheduler api04Scheduler(CollectionExecutor e,ObjectProvider<CiqVmsCollector>c){return new CiqApi04Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi05Scheduler api05Scheduler(CollectionExecutor e,ObjectProvider<CiqFaultyTrafficLightsCollector>c){return new CiqApi05Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi06Scheduler api06Scheduler(CollectionExecutor e,ObjectProvider<CiqRoadWorksCollector>c){return new CiqApi06Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi07Scheduler api07Scheduler(CollectionExecutor e,ObjectProvider<CiqTrafficFlowCollector>c){return new CiqApi07Scheduler(e,c);}
 @Bean @ConditionalOnProperty(prefix="traffic.ciq.schedule",name="enabled",havingValue="true") CiqApi08Scheduler api08Scheduler(CollectionExecutor e,ObjectProvider<CiqRoadOpeningsCollector>c){return new CiqApi08Scheduler(e,c);}
}
