<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import DashboardHeader from '../components/dashboard/DashboardHeader.vue'
import VehicleMap from '../components/dashboard/VehicleMap.vue'
import AcquisitionTrend from '../components/dashboard/AcquisitionTrend.vue'
import { cities, type CityCode } from '../config/cities'
import { dashboardApi, type Acquisition, type Anomaly, type ApiRequest, type Overview, type RouteShape, type RouteTrace, type SystemStatus, type TrendPoint, type Vehicle } from '../api/dashboardApi'
import { useDashboardRefresh } from '../composables/useDashboardRefresh'
const {t,locale}=useI18n();const selected=ref<CityCode>('JB');const city=computed(()=>cities.find(c=>c.code===selected.value)!)
const vehicles=ref<Vehicle[]>([]),routeTraces=ref<RouteTrace[]>([]),roadShapes=ref<RouteShape[]>([]),focusedRoute=ref<string>(),showAllRoutes=ref(false),acquisition=ref<Acquisition[]>([]),trend=ref<TrendPoint[]>([]),overview=ref<Overview>(),anomalies=ref<Anomaly[]>([]),requests=ref<ApiRequest[]>([]),status=ref<SystemStatus>();const updated=ref<string>();const loadingMap=ref(true),mapError=ref('')
const number=(v?:number)=>v==null?'--':new Intl.NumberFormat(locale.value==='zh'?'zh-CN':'en-US',{maximumFractionDigits:2}).format(v)
const time=(v?:string,full=false)=>v?new Intl.DateTimeFormat(locale.value==='zh'?'zh-CN':'en-GB',{timeZone:'Asia/Kuala_Lumpur',...(full?{dateStyle:'short' as const,timeStyle:'medium' as const}:{hour:'2-digit' as const,minute:'2-digit' as const,second:'2-digit' as const}),hour12:false}).format(new Date(v)):'--'
const stateClass=(s?:string)=>String(s||'unknown').toLowerCase()
function activeRouteKeys(){return [...new Set(vehicles.value.filter(v=>Number(v.freshnessSeconds??999999)<=600).map(v=>v.routeShortName||v.resolvedRouteId).filter((v):v is string=>!!v))]}
function normalizeShapes(shapes:RouteShape[],route?:string){return shapes.map(shape=>({...shape,routeKey:shape.routeKey||route||'--'}))}
async function completeAllRoutes(){const primary=await dashboardApi.routeTraces(selected.value,undefined,true);const shapes=normalizeShapes(primary.roadShapes||[],primary.selectedRouteKey),traces=[...(primary.traces||[])];const covered=new Set(shapes.map(shape=>shape.routeKey));const missing=activeRouteKeys().filter(route=>!covered.has(route));if(missing.length){const supplements=await Promise.allSettled(missing.map(route=>dashboardApi.routeTraces(selected.value,route)));for(let index=0;index<supplements.length;index++){const item=supplements[index];if(item.status==='fulfilled'){shapes.push(...normalizeShapes(item.value.roadShapes||[],item.value.selectedRouteKey||missing[index]));traces.push(...(item.value.traces||[]))}}}
  const uniqueShapes=[...new Map(shapes.map(shape=>[`${shape.routeKey}\u0000${shape.directionId??'x'}\u0000${shape.shapeId}`,shape])).values()];const shapedRoutes=new Set(uniqueShapes.map(shape=>shape.routeKey));const fallbackTraces=[...new Map(traces.filter(trace=>!shapedRoutes.has(trace.routeKey)&&trace.points.length>1).map(trace=>[`${trace.routeKey}\u0000${trace.directionId??'x'}\u0000${trace.vehicleId}`,trace])).values()];return {shapes:uniqueShapes,traces:fallbackTraces}}
async function loadVehicles(){loadingMap.value=true;mapError.value='';try{const vehicleResult=await dashboardApi.vehicles(selected.value);vehicles.value=vehicleResult.vehicles;updated.value=vehicleResult.generatedAt}catch(error){vehicles.value=[];mapError.value=String(error);loadingMap.value=false;return}try{if(showAllRoutes.value){const complete=await completeAllRoutes();roadShapes.value=complete.shapes;routeTraces.value=complete.traces}else{const result=await dashboardApi.routeTraces(selected.value,focusedRoute.value);routeTraces.value=result.traces;roadShapes.value=normalizeShapes(result.roadShapes||[],result.selectedRouteKey||focusedRoute.value);if(result.selectedRouteKey)focusedRoute.value=result.selectedRouteKey}}catch{routeTraces.value=[];roadShapes.value=[]}finally{loadingMap.value=false}}
async function focusRoute(route:string){if(route===focusedRoute.value&&!showAllRoutes.value)return;showAllRoutes.value=false;loadingMap.value=true;mapError.value='';try{const result=await dashboardApi.routeTraces(selected.value,route);focusedRoute.value=result.selectedRouteKey;routeTraces.value=result.traces;roadShapes.value=normalizeShapes(result.roadShapes||[],result.selectedRouteKey||route)}catch(error){mapError.value=String(error)}finally{loadingMap.value=false}}
async function toggleAllRoutes(){showAllRoutes.value=!showAllRoutes.value;loadingMap.value=true;mapError.value='';try{if(showAllRoutes.value){const complete=await completeAllRoutes();roadShapes.value=complete.shapes;routeTraces.value=complete.traces}else{const result=await dashboardApi.routeTraces(selected.value,focusedRoute.value);if(result.selectedRouteKey)focusedRoute.value=result.selectedRouteKey;routeTraces.value=result.traces;roadShapes.value=normalizeShapes(result.roadShapes||[],result.selectedRouteKey||focusedRoute.value)}}catch(error){showAllRoutes.value=!showAllRoutes.value;mapError.value=String(error)}finally{loadingMap.value=false}}
async function loadAll(){const jobs=await Promise.allSettled([dashboardApi.acquisition(),dashboardApi.trend(),dashboardApi.overview(),dashboardApi.anomalies(),dashboardApi.requests(),dashboardApi.status()]);if(jobs[0].status==='fulfilled')acquisition.value=jobs[0].value;if(jobs[1].status==='fulfilled')trend.value=jobs[1].value;if(jobs[2].status==='fulfilled')overview.value=jobs[2].value;if(jobs[3].status==='fulfilled')anomalies.value=jobs[3].value.data;if(jobs[4].status==='fulfilled')requests.value=jobs[4].value.data;if(jobs[5].status==='fulfilled')status.value=jobs[5].value}
function selectCity(code:CityCode){selected.value=code;focusedRoute.value=undefined;showAllRoutes.value=false;loadVehicles()}
function refresh(){loadVehicles();loadAll()}onMounted(refresh);useDashboardRefresh(refresh)
const kpis=computed(()=>[
  {icon:'▣',label:t('activeVehicles'),value:number(overview.value?.activeVehicles),tone:'cyan'},
  {icon:'⇩',label:t('todayRecords'),value:number(overview.value?.todayRecords),tone:'blue'},
  {icon:'◉',label:t('yesterdayRecords'),value:number(overview.value?.yesterdayRecords),tone:'violet'},
  {icon:'▤',label:t('totalRecords'),value:number(overview.value?.totalRecords)+(overview.value?.totalRecordsEstimated?` ${t('estimated')}`:''),tone:'blue'},
  {icon:'◷',label:t('latestGps'),value:time(overview.value?.latestGpsUpdate),tone:'cyan'},
  {icon:'▲',label:t('abnormalVehicles'),value:number(overview.value?.abnormalVehicles),tone:'red'},
  {icon:'◔',label:t('apiSuccessRate'),value:overview.value?.apiSuccessRate==null?'--':overview.value.apiSuccessRate.toFixed(2)+'%',tone:'green'}])
</script>
<template><main class="dashboard-page">
  <DashboardHeader :status="status" />
  <section class="top-grid">
    <article class="tech-panel map-panel"><h2><b>1</b>{{t('routeMonitor')}}</h2><nav class="city-tabs"><button v-for="item in cities" :key="item.code" :class="{active:selected===item.code}" @click="selectCity(item.code)"><span>⌖</span>{{locale==='zh'?item.nameZh:item.nameEn}} <small v-if="item.code==='JB'">(JB)</small><small v-if="item.code==='KL'">(KL)</small></button></nav><VehicleMap :city="city" :vehicles="vehicles" :route-traces="routeTraces" :road-shapes="roadShapes" :selected-route="focusedRoute" :show-all-routes="showAllRoutes" :loading="loadingMap" :error="mapError" :updated-at="updated" @route-change="focusRoute" @toggle-all-routes="toggleAllRoutes" @retry="loadVehicles" /></article>
    <article class="tech-panel acquisition-panel"><h2><b>2</b>{{t('acquisitionMonitor')}}</h2><div class="city-cards"><div v-for="item in acquisition" :key="item.cityCode" class="city-card" :class="stateClass(item.apiStatus)"><h3>{{item.cityName}} <small>({{item.cityCode}})</small></h3><dl><dt>{{t('latestRequest')}}</dt><dd>{{time(item.latestRequest)}}</dd><dt>{{t('apiStatus')}}</dt><dd><span class="status-pill" :class="stateClass(item.apiStatus)">{{item.apiStatus}}</span></dd><dt>{{t('todayRecords')}}</dt><dd>{{number(item.todayRecords)}}</dd><dt>{{t('yesterdayRecords')}}</dt><dd>{{number(item.yesterdayRecords)}}</dd><dt>{{t('insertedRecords')}}</dt><dd>{{number(item.insertedRecords)}}</dd><dt>{{t('anomalies')}}</dt><dd :class="{danger:item.anomalies>0}">{{number(item.anomalies)}}</dd></dl></div></div><div class="trend-box"><h3>{{t('trend')}}</h3><AcquisitionTrend :points="trend" /></div></article>
  </section>
  <section class="tech-panel operations"><h2><b>3</b>{{t('operationMonitor')}}</h2><div class="kpi-grid"><div v-for="kpi in kpis" :key="kpi.label" class="kpi" :class="kpi.tone"><span class="kpi-icon">{{kpi.icon}}</span><div><label>{{kpi.label}}</label><strong>{{kpi.value}}</strong></div></div></div><div class="tables-grid"><div class="data-table"><h3>{{t('recentAnomalies')}}</h3><div class="table-scroll"><table><thead><tr><th>{{t('time')}}</th><th>{{t('city')}}</th><th>{{t('vehicleId')}}</th><th>{{t('route')}}</th><th>{{t('type')}}</th><th>{{t('status')}}</th></tr></thead><tbody><tr v-for="row in anomalies" :key="row.cityCode+row.time+row.vehicleId"><td>{{time(row.time)}}</td><td>{{row.cityName}}</td><td>{{row.vehicleId}}</td><td>{{row.busRoute}}</td><td class="danger">{{row.anomalyType}}</td><td><span class="status-pill" :class="stateClass(row.status)">{{row.status}}</span></td></tr><tr v-if="!anomalies.length"><td colspan="6" class="empty">--</td></tr></tbody></table></div></div><div class="data-table"><h3>{{t('recentRequests')}}</h3><div class="table-scroll"><table><thead><tr><th>{{t('time')}}</th><th>{{t('city')}}</th><th>{{t('api')}}</th><th>{{t('httpStatus')}}</th><th>{{t('responseTime')}}</th><th>{{t('status')}}</th></tr></thead><tbody><tr v-for="row in requests" :key="row.cityCode+row.time"><td>{{time(row.time)}}</td><td>{{row.cityName}}</td><td>{{row.api}}</td><td>{{row.httpStatus??'--'}}</td><td>{{row.responseTimeMs==null?'--':row.responseTimeMs+' ms'}}</td><td><span class="status-pill" :class="stateClass(row.status)">{{row.status}}</span></td></tr><tr v-if="!requests.length"><td colspan="6" class="empty">--</td></tr></tbody></table></div></div></div></section>
</main></template>
